'use client';

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { getSupabaseBrowser } from '@/lib/supabaseBrowser';
import { revalidateAdminResource } from '@/lib/adminRevalidate';

const fields = [
  ['family','Family','text'], ['generation','Generation','text'], ['variant','Variant','text'], ['gamme','Series / gamme','text'], ['name','Name','text'], ['tagline','Tagline','text'],
  ['release_date','Release date','date'], ['announcement_date','Announcement date','date'], ['price','Launch price','number'], ['battery_life_h','Battery life (h)','number'], ['battery_life_h_saver','Battery saver (h)','number'], ['charging_time_h','Charging time (h)','number'], ['weight_g','Weight (g)','number'], ['case_size_mm','Case size (mm)','number'],
  ['water_rating','Water rating','text'], ['display_type','Display type','text'], ['ecosystem','Ecosystem','text'], ['os','OS','text'], ['source_primary','Primary source','text'], ['source_secondary','Secondary source','text'], ['source_checked_at','Source checked at','date'], ['data_confidence','Data confidence','text'],
];
const toggles = ['cellular','gps','nfc_payments','ecg','blood_oxygen','heart_rate','sleep_tracking','always_on_display','rugged','round_face','marquant'];
const statuses = ['released','announced','discontinued'];
const editableFields = ['brand_id', ...fields.map(([field]) => field), 'status', ...toggles, 'image_url', 'image_count', 'quality_score', 'qa_status', 'notes'];

export default function AdminSmartwatchEditor() {
  const { id } = useParams(); const router = useRouter();
  const [watch, setWatch] = useState(null); const [brands, setBrands] = useState([]); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false);
  const supabase = getSupabaseBrowser();
  useEffect(() => { async function load() { const [{ data }, { data: brandData }] = await Promise.all([supabase.from('smartwatches').select('*').eq('id', id).maybeSingle(), supabase.from('brands').select('id,name').order('name')]); setWatch(data); setBrands(brandData || []); } if (id) load(); }, [id]);
  function set(field, value) { setWatch((current) => ({ ...current, [field]: value })); }
  async function uploadImage(file) { if (!file) return; setUploading(true); setMessage(''); const form = new FormData(); form.append('file', file); form.append('watchId', id); const response = await fetch('/api/admin/upload-image', { method: 'POST', body: form }); const result = await response.json(); setUploading(false); if (!response.ok) return setMessage(result.error || 'Upload failed.'); set('image_url', result.url); set('image_count', Number(watch.image_count || 0) + 1); setMessage('Image uploaded. Save the model to publish the URL.'); }
  async function save(event) { event.preventDefault(); setSaving(true); setMessage(''); const editable = Object.fromEntries(editableFields.filter((key) => Object.prototype.hasOwnProperty.call(watch, key)).map((key) => [key, watch[key]])); const { error } = await supabase.from('smartwatches').update(editable).eq('id', id); setSaving(false); if (error) return setMessage(error.message); setMessage('Saved.'); await revalidateAdminResource('watch', id); }
  async function remove() { if (!window.confirm('Delete this smartwatch?')) return; const { error } = await supabase.from('smartwatches').delete().eq('id', id); if (error) setMessage(error.message); else { await revalidateAdminResource('watch', id); router.replace('/admin/smartwatches'); } }
  if (watch === null) return <div className="pt-12 text-dim">Loading model…</div>;
  if (!watch) return <div className="pt-12 text-dim">Model not found.</div>;
  return <main className="pt-8 pb-16"><div className="flex items-end gap-4 mb-8"><div className="mr-auto"><div className="font-mono text-xs text-accent uppercase mb-2">Catalog / Edit</div><h1 className="font-display font-bold text-3xl">{watch.name}</h1><p className="text-dim text-sm mt-1">{watch.id}</p></div><button onClick={remove} className="btn-ghost">Delete</button></div>
    <form onSubmit={save} className="space-y-8">
      <section className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 bg-panel border border-line p-5"><div><label className="field-label">Brand</label><select value={watch.brand_id || ''} onChange={(e) => set('brand_id', e.target.value)} className="field-input">{brands.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select></div>{fields.map(([field,label,type]) => <div key={field}><label className="field-label">{label}</label><input type={type} value={watch[field] ?? ''} onChange={(e) => set(field, type === 'number' ? (e.target.value === '' ? null : Number(e.target.value)) : e.target.value)} className="field-input" /></div>)}<div><label className="field-label">Status</label><select value={watch.status || 'released'} onChange={(e) => set('status', e.target.value)} className="field-input">{statuses.map((v) => <option key={v}>{v}</option>)}</select></div></section>
      <section className="bg-panel border border-line p-5"><label className="field-label">Product image</label><div className="grid sm:grid-cols-[160px_1fr] gap-5 items-start"><div className="aspect-square bg-panel2 border border-line overflow-hidden flex items-center justify-center">{watch.image_url ? <img src={watch.image_url} alt="" className="w-full h-full object-contain" /> : <span className="text-xs text-dim">No image</span>}</div><div><input type="file" accept="image/*" disabled={uploading} onChange={(e) => uploadImage(e.target.files?.[0])} className="block w-full text-sm" /><p className="text-xs text-dim mt-2">PNG, JPG, WebP or other browser-supported image. Maximum 8 MB.</p><input value={watch.image_url || ''} onChange={(e) => set('image_url', e.target.value)} placeholder="Or paste an image URL" className="field-input mt-4" />{uploading && <p className="text-xs text-accent mt-2">Uploading…</p>}</div></div></section>
      <section className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 bg-panel border border-line p-5"><h2 className="sm:col-span-2 lg:col-span-3 font-display font-semibold">Features</h2>{toggles.map((field) => <label key={field} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(watch[field])} onChange={(e) => set(field, e.target.checked)} />{field.replaceAll('_',' ')}</label>)}</section>
      <section className="grid sm:grid-cols-2 gap-4 bg-panel border border-line p-5"><div><label className="field-label">QA status</label><select value={watch.qa_status || 'NEEDS_RESEARCH'} onChange={(e) => set('qa_status', e.target.value)} className="field-input">{['VERIFIED','GOOD','INCOMPLETE','NEEDS_RESEARCH'].map((v) => <option key={v}>{v}</option>)}</select></div><div><label className="field-label">Quality score</label><input type="number" min="0" max="100" value={watch.quality_score ?? 0} onChange={(e) => set('quality_score', Math.max(0, Math.min(100, Number(e.target.value))))} className="field-input" /></div></section>
      <section className="bg-panel border border-line p-5"><label className="field-label">Editorial / research notes</label><textarea rows="6" value={watch.notes || ''} onChange={(e) => set('notes', e.target.value)} className="field-input" /></section>
      <div className="flex items-center gap-4"><button disabled={saving || uploading} className="btn-primary">{saving ? 'Saving…' : 'Save changes'}</button>{message && <span className="text-dim text-sm">{message}</span>}</div>
    </form></main>;
}
