import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getAllWatches, getBrands } from '@/lib/queries';
import { canonicalFor, JsonLd, SITE_URL } from '@/lib/seo';

export const revalidate = 3600;

const METRICS = {
  battery: { title: 'Battery life', intro: 'How smartwatch endurance has changed across generations.', field: 'battery_life_h', unit: 'h', higher: true },
  price: { title: 'Price', intro: 'How launch pricing has evolved across the smartwatch category.', field: 'price', unit: 'USD', higher: false },
  weight: { title: 'Weight', intro: 'How hardware weight has shifted as smartwatches evolved.', field: 'weight_g', unit: 'g', higher: false },
  display: { title: 'Display size', intro: 'How case and display dimensions have changed over time.', field: 'screen_size_mm', unit: 'mm', higher: true },
};
const FEATURE_GROUPS = {
  health: { title: 'Health technology', intro: 'Track the adoption of health sensors and wellness features across smartwatch generations.', features: [['ECG', 'ecg'], ['Blood oxygen / SpO₂', 'blood_oxygen']] },
  connectivity: { title: 'Connectivity technology', intro: 'Track how connected smartwatches have become across generations.', features: [['GPS', 'gps'], ['Cellular / LTE', 'cellular'], ['NFC payments', 'nfc_payments']] },
};
function valueOf(watch, field) { const value = Number(watch[field]); return Number.isFinite(value) ? value : null; }
function yearOf(watch) { const year = new Date(watch.release_date).getFullYear(); return Number.isFinite(year) ? year : null; }
function hasFeature(watch, field) { const value = watch[field]; return value === true || value === 1 || value === 'true' || value === '1' || (typeof value === 'string' && value.trim().toLowerCase() === 'yes'); }
export async function generateStaticParams() { return [...Object.keys(METRICS), ...Object.keys(FEATURE_GROUPS), 'brands'].map((metric) => ({ metric })); }
export async function generateMetadata({ params }) { const config = METRICS[params.metric] || FEATURE_GROUPS[params.metric] || (params.metric === 'brands' ? { title: 'Brand insights', intro: 'Explore how smartwatch brands shape the category over time.' } : null); if (!config) return {}; return { title: `${config.title} Insights | SmartwatchTimeline`, description: config.intro, ...canonicalFor(`/insights/${params.metric}`) }; }

export default async function InsightPage({ params }) {
  const metric = METRICS[params.metric]; const group = FEATURE_GROUPS[params.metric]; const isBrands = params.metric === 'brands';
  if (!metric && !group && !isBrands) notFound();
  const [watches, brands] = await Promise.all([getAllWatches(), getBrands()]);
  if (group) {
    const years = [...new Set(watches.map(yearOf).filter(Boolean))].sort((a, b) => a - b);
    const trends = group.features.map(([label, field]) => ({ label, field, count: watches.filter((w) => hasFeature(w, field)).length, byYear: years.map((year) => { const models = watches.filter((w) => yearOf(w) === year); const adopted = models.filter((w) => hasFeature(w, field)).length; return { year, adopted, total: models.length, rate: models.length ? (adopted / models.length) * 100 : 0 }; }) }));
    const jsonLd = { '@context': 'https://schema.org', '@type': 'Dataset', name: `${group.title} — SmartwatchTimeline`, description: group.intro, url: `${SITE_URL}/insights/${params.metric}` };
    return <><JsonLd data={jsonLd} /><article className="max-w-5xl mx-auto"><Link href="/insights" className="font-mono text-xs text-accent uppercase tracking-wider">← All insights</Link><div className="font-mono text-xs text-accent uppercase tracking-[0.14em] mt-8 mb-3">SmartwatchTimeline / technology</div><h1 className="font-display font-bold text-[40px] sm:text-[58px] leading-[1.05] max-w-4xl">{group.title} over time.</h1><p className="text-dim text-[15px] sm:text-[18px] leading-7 max-w-2xl mt-5">{group.intro}</p><div className="space-y-5 mt-10">{trends.map((trend) => <section key={trend.field} className="bg-panel border border-line rounded-2xl p-5 sm:p-7"><div className="flex justify-between gap-4 mb-7"><div><div className="font-mono text-[9px] text-accent uppercase tracking-wider">Feature adoption</div><h2 className="font-display font-semibold text-2xl mt-1">{trend.label}</h2></div><span className="font-mono text-xs text-dim">{trend.count} / {watches.length} models</span></div><div className="space-y-4">{trend.byYear.map((row) => <div key={row.year}><div className="flex justify-between gap-4 mb-2"><Link href={`/years/${row.year}`} className="font-mono text-xs hover:text-accent">{row.year}</Link><span className="font-mono text-xs">{row.rate.toFixed(0)}% <span className="text-dim">· {row.adopted}/{row.total}</span></span></div><div className="h-2 rounded-full bg-panel2 overflow-hidden"><div className="h-full bg-accent rounded-full" style={{ width: `${row.rate}%` }} /></div></div>)}</div></section>)}</div><div className="flex flex-wrap gap-3 mt-10"><Link href="/technologies" className="btn-primary">Browse technologies</Link><Link href="/compare" className="btn-secondary">Compare models</Link></div></article></>;
  }
  if (isBrands) {
    const stats = brands.map((brand) => { const models = watches.filter((w) => String(w.brand_id) === String(brand.id)); const priced = models.map((w) => valueOf(w, 'price')).filter((v) => v !== null); const battery = models.map((w) => valueOf(w, 'battery_life_h')).filter((v) => v !== null); const years = models.map(yearOf).filter(Boolean); return { brand, models, avgPrice: priced.length ? priced.reduce((a,b) => a+b,0)/priced.length : null, avgBattery: battery.length ? battery.reduce((a,b) => a+b,0)/battery.length : null, first: years.length ? Math.min(...years) : null, last: years.length ? Math.max(...years) : null }; }).filter((x) => x.models.length).sort((a,b) => b.models.length - a.models.length);
    const jsonLd = { '@context': 'https://schema.org', '@type': 'Dataset', name: 'Smartwatch brand insights — SmartwatchTimeline', description: 'Explore smartwatch brand trajectories, catalog size, pricing and endurance.', url: `${SITE_URL}/insights/brands` };
    return <><JsonLd data={jsonLd} /><article className="max-w-6xl mx-auto"><Link href="/insights" className="font-mono text-xs text-accent uppercase tracking-wider">← All insights</Link><div className="font-mono text-xs text-accent uppercase tracking-[0.14em] mt-8 mb-3">SmartwatchTimeline / brands</div><h1 className="font-display font-bold text-[40px] sm:text-[58px] leading-[1.05] max-w-4xl">How brands shape the category.</h1><p className="text-dim text-[15px] sm:text-[18px] leading-7 max-w-2xl mt-5">Compare the breadth, pricing and endurance of every tracked smartwatch brand.</p><div className="grid md:grid-cols-2 gap-4 mt-10">{stats.map((item) => <Link key={item.brand.id} href={`/brands/${item.brand.id}`} className="bg-panel border border-line rounded-2xl p-6 hover:border-accent transition-colors"><div className="flex items-start justify-between gap-4"><div><div className="font-mono text-[9px] text-accent uppercase tracking-wider">Brand</div><h2 className="font-display font-semibold text-2xl mt-1">{item.brand.name}</h2></div><span className="font-mono text-xs text-dim">{item.models.length} models</span></div><div className="grid grid-cols-2 gap-3 mt-6"><div><div className="font-display text-xl">{item.avgPrice === null ? '—' : `$${item.avgPrice.toFixed(0)}`}</div><div className="font-mono text-[9px] text-dim uppercase">Avg. price</div></div><div><div className="font-display text-xl">{item.avgBattery === null ? '—' : `${item.avgBattery.toFixed(1)}h`}</div><div className="font-mono text-[9px] text-dim uppercase">Avg. battery</div></div></div><div className="font-mono text-[10px] text-dim mt-5">{item.first} → {item.last}</div></Link>)}</div><div className="flex flex-wrap gap-3 mt-10"><Link href="/brands" className="btn-primary">Browse brands</Link><Link href="/timeline" className="btn-secondary">Open timeline</Link></div></article></>;
  }
  const byYear = new Map();
  for (const watch of watches) { const year = yearOf(watch); const value = valueOf(watch, metric.field); if (!year || value === null) continue; if (!byYear.has(year)) byYear.set(year, []); byYear.get(year).push(value); }
  const rows = [...byYear.entries()].sort((a, b) => a[0] - b[0]).map(([year, values]) => ({ year, average: values.reduce((a, b) => a + b, 0) / values.length, count: values.length })).filter((row) => row.count > 0); if (!rows.length) notFound();
  const min = Math.min(...rows.map((r) => r.average)); const max = Math.max(...rows.map((r) => r.average)); const latest = rows.at(-1); const first = rows[0]; const change = first.average ? ((latest.average - first.average) / first.average) * 100 : null;
  const jsonLd = { '@context': 'https://schema.org', '@type': 'Dataset', name: `${metric.title} — SmartwatchTimeline`, description: metric.intro, url: `${SITE_URL}/insights/${params.metric}`, temporalCoverage: `${first.year}/${latest.year}`, variableMeasured: metric.title };
  return <><JsonLd data={jsonLd} /><article className="max-w-5xl mx-auto"><Link href="/insights" className="font-mono text-xs text-accent uppercase tracking-wider">← All insights</Link><div className="font-mono text-xs text-accent uppercase tracking-[0.14em] mt-8 mb-3">SmartwatchTimeline / insights</div><h1 className="font-display font-bold text-[40px] sm:text-[58px] leading-[1.05] max-w-4xl">{metric.title} over time.</h1><p className="text-dim text-[15px] sm:text-[18px] leading-7 max-w-2xl mt-5">{metric.intro}</p><section className="grid grid-cols-2 lg:grid-cols-4 gap-3 mt-10 mb-10">{[[first.average, 'First tracked average', metric.unit],[latest.average, 'Latest tracked average', metric.unit],[change, 'Change since first year', '%'],[rows.length, 'Years analyzed', 'years']].map(([v,l,u]) => <div key={l} className="bg-panel border border-line rounded-2xl p-5"><div className="font-display font-bold text-2xl">{typeof v === 'number' ? `${v.toFixed(1)}${u === '%' ? '%' : ''}` : '—'}{u !== '%' && u !== 'years' ? <span className="text-sm text-dim ml-1">{u}</span> : null}</div><div className="font-mono text-[9px] text-dim uppercase tracking-wider mt-2">{l}</div></div>)}</section><section className="bg-panel border border-line rounded-2xl p-5 sm:p-7 mb-10"><div className="font-mono text-[9px] text-accent uppercase tracking-wider">Annual trend</div><h2 className="font-display font-semibold text-2xl mt-1 mb-7">Average {metric.title.toLowerCase()}</h2><div className="space-y-4">{rows.map((row) => { const width = max === min ? 100 : 18 + ((row.average - min) / (max - min)) * 82; return <div key={row.year}><div className="flex justify-between gap-4 mb-2"><Link href={`/years/${row.year}`} className="font-mono text-xs hover:text-accent">{row.year}</Link><span className="font-mono text-xs">{row.average.toFixed(1)} {metric.unit} <span className="text-dim">· {row.count} models</span></span></div><div className="h-2 rounded-full bg-panel2 overflow-hidden"><div className="h-full bg-accent rounded-full" style={{ width: `${width}%` }} /></div></div>; })}</div></section><div className="flex flex-wrap gap-3"><Link href="/compare" className="btn-primary">Compare models</Link><Link href="/timeline" className="btn-secondary">Open timeline</Link><Link href="/insights" className="btn-secondary">More insights</Link></div></article></>;
}
